CREATE DATABASE IF NOT EXISTS `poo`
  CHARACTER SET = utf8mb4
  COLLATE = utf8mb4_0900_ai_ci;
CREATE USER IF NOT EXISTS
  'poo'@'localhost'
  IDENTIFIED BY 'poo'
  FAILED_LOGIN_ATTEMPTS 3
  PASSWORD_LOCK_TIME 7;
GRANT ALL ON `poo`.* TO 'poo'@'localhost';

USE `poo`;
